---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: today
spec:
  replicas: 1
  selector:
    matchLabels:
      name: today
  template:
    metadata:
      labels:
        name: today
    spec:
      containers:
      - name: application
        image: anirudhteam/today
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
